/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 4f3dd8675adc288a2bcf5c4b2184f841)
interface __BaseEnv_CloudflareEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	NEXT_TAG_CACHE_D1: D1Database;
	NEXT_CACHE_DO_QUEUE: DurableObjectNamespace /* DOQueueHandler */;
	COMMENT_LIMITER: RateLimit;
	LIKE_LIMITER: RateLimit;
	EARLY_ACCESS_LIMITER: RateLimit;
	COMMENT_EDIT_LIMITER: RateLimit;
	EA_PAGE_LIMITER: RateLimit;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	R2_ACCOUNT_ID: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_ENDPOINT: string;
	R2_PUBLIC_URL: string;
	NEXT_PUBLIC_RECAPTCHA_SITE_KEY: string;
	RECAPTCHA_SECRET_KEY: string;
	NEXT_PUBLIC_EARLY_ACCESS_ENABLED: string;
	R2_EA_BUCKET_NAME: string;
	R2_BUCKET_NAME: string;
	ADMIN_USER_ID: string;
	NEXT_PUBLIC_SITE_URL: string;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_SUPABASE_URL" | "NEXT_PUBLIC_SUPABASE_ANON_KEY" | "SUPABASE_SERVICE_ROLE_KEY" | "R2_ACCOUNT_ID" | "R2_ACCESS_KEY_ID" | "R2_SECRET_ACCESS_KEY" | "R2_ENDPOINT" | "R2_PUBLIC_URL" | "NEXT_PUBLIC_RECAPTCHA_SITE_KEY" | "RECAPTCHA_SECRET_KEY" | "NEXT_PUBLIC_EARLY_ACCESS_ENABLED" | "R2_EA_BUCKET_NAME" | "R2_BUCKET_NAME" | "ADMIN_USER_ID" | "NEXT_PUBLIC_SITE_URL">> {}
}
